package yy;

/**
 * @author YellowAfterlife
 */
typedef YyProject = {
	resources:Array<{
		id:{
			name:String,
			path:String
		},
		order:Int
	}>,
	Options:Array<{
		name:String,
		path:String
	}>,
	isDnDProject:Bool,
	isEcma:Bool,
	tutorialPath:String,
	configs:{
		name:String,
		children:Array<Any>
	},
	RoomOrderNodes:Array<{
		roomId:{
			name:String,
			path:String
		}
	}>,
	Folders:Array<{
		folderPath:String,
		order:Int,
		resourceVersion:String,
		name:String,
		tags:Array<Any>,
		resourceType:String
	}>,
	AudioGroups:Array<{
		targets:Int,
		resourceVersion:String,
		name:String,
		resourceType:String
	}>,
	TextureGroups:Array<{
		isScaled:Bool,
		autocrop:Bool,
		border:Int,
		mipsToGenerate:Int,
		groupParent:Any,
		targets:Int,
		resourceVersion:String,
		name:String,
		resourceType:String
	}>,
	IncludedFiles:Array<{
		CopyToMask:Int,
		filePath:String,
		resourceVersion:String,
		name:String,
		resourceType:String
	}>,
	MetaData:{
		IDEVersion:String
	},
	resourceVersion:String,
	name:String,
	tags:Array<Any>,
	resourceType:String
}