package yy;
import haxe.DynamicAccess;

/**
 * Generated using
 * https://yal.cc/r/19/json2typedef/
 * @author YellowAfterlife
 */
typedef YySprite = {
	resourceType:String,
	resourceVersion:String,
	name:String,
	bboxMode:Int,
	collisionKind:Int,
	type:Int,
	origin:Int,
	preMultiplyAlpha:Bool,
	edgeFiltering:Bool,
	collisionTolerance:Int,
	swfPrecision:Float,
	bbox_left:Int,
	bbox_right:Int,
	bbox_top:Int,
	bbox_bottom:Int,
	HTile:Bool,
	VTile:Bool,
	For3D:Bool,
	DynamicTexturePage:Bool,
	width:Int,
	height:Int,
	textureGroupId:{
		name:String,
		path:String
	},
	swatchColours:Any,
	gridX:Int,
	gridY:Int,
	frames:Array<{
		resourceType:String,
		resourceVersion:String,
		name:String,
		// the following were eliminated in GM2022:
		?compositeImage:{
			FrameId:{
				name:String,
				path:String
			},
			LayerId:Any,
			resourceVersion:String,
			name:String,
			tags:Array<Any>,
			resourceType:String
		},
		?images:Array<{
			FrameId:{
				name:String,
				path:String
			},
			LayerId:{
				name:String,
				path:String
			},
			resourceVersion:String,
			name:String,
			tags:Array<Any>,
			resourceType:String
		}>,
		?parent:{
			name:String,
			path:String
		},
	}>,
	sequence:{
		resourceType:String,
		resourceVersion:String,
		name:String,
		timeUnits:Int,
		playback:Int,
		playbackSpeed:Float,
		playbackSpeedType:Int,
		autoRecord:Bool,
		volume:Float,
		length:Float,
		events:{
			Keyframes:Array<Any>,
			resourceVersion:String,
			resourceType:String
		},
		moments:{
			Keyframes:Array<Any>,
			resourceVersion:String,
			resourceType:String
		},
		tracks:Array<{
			resourceType:String,
			resourceVersion:String,
			name:String,
			spriteId:Any,
			keyframes:{
				Keyframes:Array<{
					id:String,
					Key:Float,
					Length:Float,
					Stretch:Bool,
					Disabled:Bool,
					IsCreationKey:Bool,
					Channels:DynamicAccess<{
						Id:{
							name:String,
							path:String
						},
						resourceVersion:String,
						resourceType:String
					}>,
					resourceVersion:String,
					resourceType:String
				}>,
				resourceVersion:String,
				resourceType:String
			},
			trackColour:Int,
			inheritsTrackColour:Bool,
			builtinName:Int,
			traits:Int,
			interpolation:Int,
			tracks:Array<Any>,
			events:Array<Any>,
			isCreationTrack:Bool,
			modifiers:Array<Any>
		}>,
		visibleRange:Any,
		lockOrigin:Bool,
		showBackdrop:Bool,
		showBackdropImage:Bool,
		backdropImagePath:String,
		backdropImageOpacity:Float,
		backdropWidth:Int,
		backdropHeight:Int,
		backdropXOffset:Float,
		backdropYOffset:Float,
		xorigin:Int,
		yorigin:Int,
		eventToFunction:{},
		eventStubScript:Any
	},
	layers:Array<{
		resourceType:String,
		resourceVersion:String,
		name:String,
		visible:Bool,
		isLocked:Bool,
		blendMode:Int,
		opacity:Float,
		displayName:String
	}>,
	nineSlice:Any,
	parent:{
		name:String,
		path:String
	}
};